2024-12-15 16:20:49 UTC
Windows-10-10.0.19045
Ren'Py 8.3.4.24120703

Early init took 0.09s
Loading error handling took 0.03s
Loading script took 0.26s
Loading save slot metadata took 0.13s
Loading persistent took 0.00s
Running init code took 0.09s
Loading analysis data took 0.01s
Analyze and compile ATL took 0.02s
Reloading save slot metadata took 0.09s
Index archives took 0.00s
Backing up script files to 'C:\\Users\\Jacob\\AppData\\Roaming/RenPy/backups\\JacobMod':
Dump and make backups took 0.05s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc took 0.05s
DPI scale factor: 1.000000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Creating interface object took 0.27s
Cleaning stores took 0.00s
Init translation took 0.04s
Build styles took 0.00s
Load screen analysis took 0.00s
Analyze screens took 0.01s
Save screen analysis took 0.01s
Prepare screens took 0.05s
Save pyanalysis. took 0.00s
Save bytecode. took 0.03s
Running _start took 0.00s
Interface start took 0.07s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: "b'NVIDIA Corporation'"
Renderer: b'NVIDIA GeForce RTX 3080/PCIe/SSE2'
Version: b'4.6.0 NVIDIA 566.36'
Display Info: None
Screen sizes: virtual=(1280, 720) physical=(1920, 1017) drawable=(1920, 1017)
Maximum texture size: 4096x4096
Screen sizes: virtual=(1280, 720) physical=(1920, 1017) drawable=(1920, 1017)
Maximum texture size: 4096x4096

Full traceback:
  File "game/script.rpy", line 8, in script call
    call ch1_main from _call_ch1_main
  File "game/script-ch1.rpy", line 208, in script
    fb "hvorfor?"
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'fb' is not defined.

While running game code:
  File "game/script.rpy", line 8, in script call
    call ch1_main from _call_ch1_main
  File "game/script-ch1.rpy", line 208, in script
    fb "hvorfor?"
Exception: Sayer 'fb' is not defined.

Full traceback:
  File "game/script.rpy", line 8, in script call
    call ch1_main from _call_ch1_main
  File "game/script-ch1.rpy", line 210, in script
    fb "dårlig joke"
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'fb' is not defined.

While running game code:
  File "game/script.rpy", line 8, in script call
    call ch1_main from _call_ch1_main
  File "game/script-ch1.rpy", line 210, in script
    fb "dårlig joke"
Exception: Sayer 'fb' is not defined.

Full traceback:
  File "game/script.rpy", line 8, in script call
    call ch1_main from _call_ch1_main
  File "game/script-ch1.rpy", line 212, in script
    fb "what!,den er jo mega umulig,er det æblemanden"
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'fb' is not defined.

While running game code:
  File "game/script.rpy", line 8, in script call
    call ch1_main from _call_ch1_main
  File "game/script-ch1.rpy", line 212, in script
    fb "what!,den er jo mega umulig,er det æblemanden"
Exception: Sayer 'fb' is not defined.

Full traceback:
  File "game/script.rpy", line 8, in script call
    call ch1_main from _call_ch1_main
  File "game/script-ch1.rpy", line 214, in script
    fb "hvor skulle jeg vide det fra!"
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'fb' is not defined.

While running game code:
  File "game/script.rpy", line 8, in script call
    call ch1_main from _call_ch1_main
  File "game/script-ch1.rpy", line 214, in script
    fb "hvor skulle jeg vide det fra!"
Exception: Sayer 'fb' is not defined.

Full traceback:
  File "game/script.rpy", line 8, in script call
    call ch1_main from _call_ch1_main
  File "game/script-ch1.rpy", line 217, in script
    fb "what!,hvordan skulle jeg svare rigtigt på det,det jo bare en random person som du kender!"
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'fb' is not defined.

While running game code:
  File "game/script.rpy", line 8, in script call
    call ch1_main from _call_ch1_main
  File "game/script-ch1.rpy", line 217, in script
    fb "what!,hvordan skulle jeg svare rigtigt på det,det jo bare en random person som du kender!"
Exception: Sayer 'fb' is not defined.
