2024-12-22 12:52:31 UTC
Windows-10-10.0.19045
Ren'Py 8.3.4.24120703

Early init took 0.16s
Loading error handling took 0.03s
Loading script took 0.29s
Loading save slot metadata took 0.16s
Loading persistent took 0.00s
Running init code took 0.09s
Loading analysis data took 0.01s
Analyze and compile ATL took 0.03s
Reloading save slot metadata took 0.10s
Index archives took 0.00s
Backing up script files to 'C:\\Users\\Jacob\\AppData\\Roaming/RenPy/backups\\JacobMod':
Dump and make backups took 0.05s
Cleaning cache took 0.00s
Making clean stores took 0.00s
Initial gc took 0.04s
DPI scale factor: 1.000000
nvdrs: Loaded, about to disable thread optimizations.
nvdrs: Disabled thread optimizations.
Creating interface object took 0.26s
Cleaning stores took 0.00s
Init translation took 0.03s
Build styles took 0.00s
Load screen analysis took 0.00s
Analyze screens took 0.01s
Save screen analysis took 0.01s
Prepare screens took 0.04s
Save pyanalysis. took 0.00s
Save bytecode. took 0.03s
Running _start took 0.00s
Interface start took 0.06s

Initializing gl2 renderer:
primary display bounds: (0, 0, 1920, 1080)
swap interval: 1 frames
Windowed mode.
Vendor: "b'NVIDIA Corporation'"
Renderer: b'NVIDIA GeForce RTX 3080/PCIe/SSE2'
Version: b'4.6.0 NVIDIA 566.36'
Display Info: None
Screen sizes: virtual=(1280, 720) physical=(1920, 1017) drawable=(1920, 1017)
Maximum texture size: 4096x4096
Screen sizes: virtual=(1280, 720) physical=(1920, 1017) drawable=(1920, 1017)
Maximum texture size: 4096x4096

Full traceback:
  File "game/script.rpy", line 12, in script call
    call ch5_main from _call_ch5_main
  File "game/script-ch5.rpy", line 321, in script
    br "det må betyder uuuups jeg gjorte det igen timon"
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'br' is not defined.

While running game code:
  File "game/script.rpy", line 12, in script call
    call ch5_main from _call_ch5_main
  File "game/script-ch5.rpy", line 321, in script
    br "det må betyder uuuups jeg gjorte det igen timon"
Exception: Sayer 'br' is not defined.

Full traceback:
  File "game/script.rpy", line 12, in script call
    call ch5_main from _call_ch5_main
  File "game/script-ch5.rpy", line 323, in script
    br "ej,ahohoh.kan du trække dem op du"
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'br' is not defined.

While running game code:
  File "game/script.rpy", line 12, in script call
    call ch5_main from _call_ch5_main
  File "game/script-ch5.rpy", line 323, in script
    br "ej,ahohoh.kan du trække dem op du"
Exception: Sayer 'br' is not defined.

Full traceback:
  File "game/script.rpy", line 12, in script call
    call ch5_main from _call_ch5_main
  File "game/script-ch5.rpy", line 338, in script
    br "ahohoh,det ligesom når jeg bander elias i at tale ved at give ham ondt i halsen"
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'br' is not defined.

While running game code:
  File "game/script.rpy", line 12, in script call
    call ch5_main from _call_ch5_main
  File "game/script-ch5.rpy", line 338, in script
    br "ahohoh,det ligesom når jeg bander elias i at tale ved at give ham ondt i halsen"
Exception: Sayer 'br' is not defined.

Full traceback:
  File "game/script.rpy", line 12, in script call
    call ch5_main from _call_ch5_main
  File "game/script-ch5.rpy", line 340, in script
    br "det fordi at han ikke kan flygte fra at blive syg af mig ahohohoh,god joke"
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'br' is not defined.

While running game code:
  File "game/script.rpy", line 12, in script call
    call ch5_main from _call_ch5_main
  File "game/script-ch5.rpy", line 340, in script
    br "det fordi at han ikke kan flygte fra at blive syg af mig ahohohoh,god joke"
Exception: Sayer 'br' is not defined.

Full traceback:
  File "game/script.rpy", line 12, in script call
    call ch5_main from _call_ch5_main
  File "game/script-ch5.rpy", line 342, in script
    br "ej,falder de ned"
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'br' is not defined.

While running game code:
  File "game/script.rpy", line 12, in script call
    call ch5_main from _call_ch5_main
  File "game/script-ch5.rpy", line 342, in script
    br "ej,falder de ned"
Exception: Sayer 'br' is not defined.

Full traceback:
  File "game/script.rpy", line 12, in script call
    call ch5_main from _call_ch5_main
  File "game/script-ch5.rpy", line 355, in script
    br "man kan ikke vinde,du må ikke vinde,man kan ikke vinde,og du må ikke vinde"
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'br' is not defined.

While running game code:
  File "game/script.rpy", line 12, in script call
    call ch5_main from _call_ch5_main
  File "game/script-ch5.rpy", line 355, in script
    br "man kan ikke vinde,du må ikke vinde,man kan ikke vinde,og du må ikke vinde"
Exception: Sayer 'br' is not defined.

Full traceback:
  File "game/script.rpy", line 12, in script call
    call ch5_main from _call_ch5_main
  File "game/script-ch5.rpy", line 357, in script
    br "bro,den er mega god"
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Jacob\Desktop\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'br' is not defined.

While running game code:
  File "game/script.rpy", line 12, in script call
    call ch5_main from _call_ch5_main
  File "game/script-ch5.rpy", line 357, in script
    br "bro,den er mega god"
Exception: Sayer 'br' is not defined.
